CREATE TABLE [dbo].[BOOKS] (
    [ID]         UNIQUEIDENTIFIER DEFAULT (newsequentialid()) NOT NULL PRIMARY KEY,
    [NAME]       VARCHAR (100)    NOT NULL,
    [AUTHORNAME] VARCHAR (100)    NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);